name: multi_stream_chat
description: A chat app for streamers who streams on multiple platforms.
publish_to: none
version: "0.0.1"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  meta: ^1.8.0
  provider: ^6.0.4
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  tmi_dart:
    git:
      url: https://github.com/alanqchen/tmi_dart.git

dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
